
import { UntranslatableWord } from './types';

export const BOOK_WORDS_JSON = `
[
  {"word": "Hygge", "native_script": null, "pronunciation": "hoo-gah", "definition": "A Danish concept of cozy contentment and well-being through enjoying the simple things in life.", "origin_country": "Denmark", "origin_language": "Danish", "theme": "Comforts of Connection"},
  {"word": "Fika", "native_script": null, "pronunciation": "fee-ka", "definition": "A Swedish tradition of a scheduled and respected pause for coffee and connection, insisting that sweetness and communion are vital.", "origin_country": "Sweden", "origin_language": "Swedish", "theme": "Comforts of Connection"},
  {"word": "Sobremesa", "native_script": null, "pronunciation": "so-breh-meh-sa", "definition": "The time spent after a meal when the food is gone but the conversation continues to flow.", "origin_country": "Spain", "origin_language": "Spanish", "theme": "Comforts of Connection"},
  {"word": "Cafuné", "native_script": null, "pronunciation": "ka-foo-neh", "definition": "The tender gesture of running your fingers through a loved one's hair.", "origin_country": "Brazil", "origin_language": "Portuguese", "theme": "Comforts of Connection"},
  {"word": "Saudade", "native_script": null, "pronunciation": "sow-dah-dsh", "definition": "A melancholic, bittersweet ache for a person or place that was once real and is now gone, tinged with the pleasure of memory.", "origin_country": "Portugal", "origin_language": "Portuguese", "theme": "Aches of Absence"},
  {"word": "Hiraeth", "native_script": null, "pronunciation": "hee-raith", "definition": "A deep, grief-stricken yearning for a version of home that is now irretrievably lost, or perhaps was only ever a romanticized dream.", "origin_country": "Wales", "origin_language": "Welsh", "theme": "Aches of Absence"},
  {"word": "Toska", "native_script": null, "pronunciation": "tos-ka", "definition": "A uniquely existential anguish, a dull ache of the soul with no specific cause—a longing for nothing and everything at once.", "origin_country": "Russia", "origin_language": "Russian", "theme": "Aches of Absence"},
  {"word": "Kilig", "native_script": null, "pronunciation": "kee-leeg", "definition": "The giddy thrill and electric euphoria of a new romance or having a crush on someone.", "origin_country": "Philippines", "origin_language": "Tagalog", "theme": "Aches of Absence"},
  {"word": "Ya'aburnee", "native_script": "تقبرني", "pronunciation": "ya-ah-bur-nee", "definition": "A breathtaking devotion, translating to 'you bury me,' expressing the hope to die before a loved one to be spared the pain of living without them.", "origin_country": "Levant", "origin_language": "Arabic", "theme": "Aches of Absence"},
  {"word": "Fernweh", "native_script": null, "pronunciation": "fairn-vey", "definition": "A longing for faraway places; 'distance-sickness' or a craving for travel.", "origin_country": "Germany", "origin_language": "German", "theme": "Aches of Absence"},
  {"word": "Komorebi", "native_script": "木漏れ日", "pronunciation": "ko-mo-reh-bee", "definition": "The scattered, dappled light that filters through the leaves of trees.", "origin_country": "Japan", "origin_language": "Japanese", "theme": "In the Presence of Nature"},
  {"word": "Waldeinsamkeit", "native_script": null, "pronunciation": "vald-ayn-zahm-kite", "definition": "The sublime, spiritual feeling of solitude and connectedness one feels when alone in the woods.", "origin_country": "Germany", "origin_language": "German", "theme": "In the Presence of Nature"},
  {"word": "Gluggaveður", "native_script": null, "pronunciation": "gloo-gah-veh-dhur", "definition": "'Window-weather'; weather that looks beautiful from indoors but is, in reality, brutally cold or windy.", "origin_country": "Iceland", "origin_language": "Icelandic", "theme": "In the Presence of Nature"},
  {"word": "Gurfa", "native_script": "غرفة", "pronunciation": "ghur-fa", "definition": "The amount of water that can be held in one hand.", "origin_country": "Arabian Peninsula", "origin_language": "Arabic", "theme": "In the Presence of Nature"},
  {"word": "Wabi-sabi", "native_script": "侘寂", "pronunciation": "wah-bee sah-bee", "definition": "A worldview centered on the acceptance of transience and imperfection; finding serene beauty in the imperfect, impermanent, and incomplete.", "origin_country": "Japan", "origin_language": "Japanese", "theme": "Inner World"},
  {"word": "Sisu", "native_script": null, "pronunciation": "see-soo", "definition": "A form of gritty, stoic determination and resilience in the face of extreme adversity; a psychological reserve of strength.", "origin_country": "Finland", "origin_language": "Finnish", "theme": "Inner World"},
  {"word": "Ikigai", "native_script": "生き甲斐", "pronunciation": "ee-kee-guy", "definition": "A 'reason for being'; the energizing force that gets one out of bed in the morning, a sense of purpose.", "origin_country": "Japan", "origin_language": "Japanese", "theme": "Inner World"},
  {"word": "L'esprit de l'escalier", "native_script": null, "pronunciation": "les-pree duh les-kal-yay", "definition": "'Staircase wit'; the torment of thinking of the perfect comeback only after the conversation is over.", "origin_country": "France", "origin_language": "French", "theme": "Peculiar Human Condition"},
  {"word": "Tsundoku", "native_script": "積読", "pronunciation": "tsun-doh-koo", "definition": "The act of buying books and letting them pile up, unread, like monuments to good intentions.", "origin_country": "Japan", "origin_language": "Japanese", "theme": "Peculiar Human Condition"},
  {"word": "Kummerspeck", "native_script": null, "pronunciation": "koo-mer-shpek", "definition": "'Grief bacon'; weight gained from emotional eating.", "origin_country": "Germany", "origin_language": "German", "theme": "Peculiar Human Condition"},
  {"word": "Tartle", "native_script": null, "pronunciation": "tar-tuhl", "definition": "The brief, panicked hesitation when you have to introduce someone whose name you have just forgotten.", "origin_country": "Scotland", "origin_language": "Scots", "theme": "Peculiar Human Condition"},
  {"word": "Boketto", "native_script": "ぼーっと", "pronunciation": "boh-ket-toh", "definition": "The act of gazing vacantly into the distance without a thought.", "origin_country": "Japan", "origin_language": "Japanese", "theme": "Peculiar Human Condition"}
]
`;

export const WORDS_LIST: UntranslatableWord[] = JSON.parse(BOOK_WORDS_JSON);
